# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Robotilsa_HMI_2ndW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondaryWindow(object):
    def setupUi(self, SecondaryWindow):
        SecondaryWindow.setObjectName("SecondaryWindow")
        SecondaryWindow.resize(300, 380)
        SecondaryWindow.setMaximumSize(QtCore.QSize(300, 380))
        SecondaryWindow.setSizeIncrement(QtCore.QSize(0, 0))
        SecondaryWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        SecondaryWindow.setAnimated(True)
        SecondaryWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(SecondaryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lst_info = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.lst_info.setFont(font)
        self.lst_info.setObjectName("lst_info")
        self.horizontalLayout.addWidget(self.lst_info)
        SecondaryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SecondaryWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondaryWindow)

    def retranslateUi(self, SecondaryWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondaryWindow.setWindowTitle(_translate("SecondaryWindow", "Ventana Secundaria (Info)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondaryWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondaryWindow()
    ui.setupUi(SecondaryWindow)
    SecondaryWindow.show()
    sys.exit(app.exec_())
